Checkout dev and Set dev branch

diff --git a/git-dev-update b/git-dev-update
--- a/git-dev-update
+++ b/git-dev-update
@@ -6,79 +6,79 @@ RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`
 source ${RUN_PATH}/_git_def.sh
 
 cd $PWD
-BRANCH=$(git rev-parse --abbrev-ref HEAD)
+BRANCH_CURRENT=$(git rev-parse --abbrev-ref HEAD)
 
-if [ -f './.git/branch_dev' ]; then
-  BRANCH_DEV=$(cat './.git/branch_dev')
+if [ -f "${BRANCH_DEV_FILE}" ]; then
+  BRANCH_DEV=$(cat "${BRANCH_DEV_FILE}")
 else
   BRANCH_DEV='dev'
 fi
 
-if [ "$BRANCH" == "" ]; then
+if [ "${BRANCH_CURRENT}" == "" ]; then
   echo "... Error: empty branch"
 else
-  if [ "$BRANCH" == "$BRANCH_DEV" ]; then
-    echo "... Error:  you are already in dev branch '$BRANCH_DEV'"
+  if [ "${BRANCH_CURRENT}" == "${BRANCH_DEV}" ]; then
+    echo "... Error:  you are already in dev branch '${BRANCH_DEV}'"
   else  
     echo ""
-    echo -e $BS">> Current branch '"$BRANCH"' <<"$BE
+    echo -e $BS">> Current branch '"${BRANCH_CURRENT}"' <<"$BE
     echo ""
     
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: checkout "$BRANCH_DEV$BE
+    echo -e $BS"Run command: checkout "${BRANCH_DEV}$BE
     echo "--------------------------------------------------------"
-    git checkout $BRANCH_DEV
+    git checkout ${BRANCH_DEV}
     exit_on_error $? !!
     echo "--------------------------------------------------------"
     echo -e $BS"Run command: fetch origin (get branch list)"$BE
     echo "--------------------------------------------------------"
     git fetch origin
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: pull origin $BRANCH_DEV (update $BRANCH_DEV)"$BE
+    echo -e $BS"Run command: pull origin ${BRANCH_DEV} (update ${BRANCH_DEV})"$BE
     echo "--------------------------------------------------------"
-    git pull --no-commit origin $BRANCH_DEV
+    git pull --no-commit origin ${BRANCH_DEV}
     exit_on_error $? !!
     git add -A
-    git commit -m "Merge branch '$BRANCH_DEV'"
+    git commit -m "Merge branch '${BRANCH_DEV}'"
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: checkout "$BRANCH$BE
+    echo -e $BS"Run command: checkout "${BRANCH_CURRENT}$BE
     echo "--------------------------------------------------------"
-    git checkout $BRANCH
+    git checkout ${BRANCH_CURRENT}
     exit_on_error $? !!
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: pull origin "$BRANCH" (update "$BRANCH")"$BE
+    echo -e $BS"Run command: pull origin "${BRANCH_CURRENT}" (update "${BRANCH_CURRENT}")"$BE
     echo "--------------------------------------------------------"
-    git pull --no-commit origin $BRANCH
-    exit_on_error $? !!
-    git add -A
-    git commit -m "Merge branch '"$BRANCH"'"
-    echo "--------------------------------------------------------"
-    echo -e $BS"Run command: pull origin $BRANCH_DEV (merge $BRANCH_DEV to "$BRANCH")"$BE
-    echo "--------------------------------------------------------"
-    git pull --no-commit origin $BRANCH_DEV
+    git pull --no-commit origin ${BRANCH_CURRENT}
     exit_on_error $? !!
     git add -A
-    git commit -m "Merge branch '$BRANCH_DEV' to '"$BRANCH"'"
+    git commit -m "Merge branch '"${BRANCH_CURRENT}"'"
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: push origin "$BRANCH$BE
+    echo -e $BS"Run command: pull origin ${BRANCH_DEV} (merge ${BRANCH_DEV} to "${BRANCH_CURRENT}")"$BE
     echo "--------------------------------------------------------"
-    git push origin $BRANCH
-    exit_on_error $? !!
-    echo "--------------------------------------------------------"
-    echo -e $BS"Run command: checkout $BRANCH_DEV"$BE
-    echo "--------------------------------------------------------"
-    git checkout $BRANCH_DEV
-    exit_on_error $? !!
-    echo "--------------------------------------------------------"
-    echo -e $BS"Run command: pull origin "$BRANCH" (merge "$BRANCH" to $BRANCH_DEV)"$BE
-    echo "--------------------------------------------------------"
-    git pull --no-commit origin $BRANCH
+    git pull --no-commit origin ${BRANCH_DEV}
     exit_on_error $? !!
     git add -A
-    git commit -m "Merge branch '"$BRANCH"' to '$BRANCH_DEV'"
+    git commit -m "Merge branch '${BRANCH_DEV}' to '"${BRANCH_CURRENT}"'"
     echo "--------------------------------------------------------"
-    echo -e $BS"Run command: push origin $BRANCH_DEV"$BE
+    echo -e $BS"Run command: push origin "${BRANCH_CURRENT}$BE
     echo "--------------------------------------------------------"
-    git push origin $BRANCH_DEV
+    git push origin ${BRANCH_CURRENT}
+    exit_on_error $? !!
+    echo "--------------------------------------------------------"
+    echo -e $BS"Run command: checkout ${BRANCH_DEV}"$BE
+    echo "--------------------------------------------------------"
+    git checkout ${BRANCH_DEV}
+    exit_on_error $? !!
+    echo "--------------------------------------------------------"
+    echo -e $BS"Run command: pull origin "${BRANCH_CURRENT}" (merge "${BRANCH_CURRENT}" to ${BRANCH_DEV})"$BE
+    echo "--------------------------------------------------------"
+    git pull --no-commit origin ${BRANCH_CURRENT}
+    exit_on_error $? !!
+    git add -A
+    git commit -m "Merge branch '"${BRANCH_CURRENT}"' to '${BRANCH_DEV}'"
+    echo "--------------------------------------------------------"
+    echo -e $BS"Run command: push origin ${BRANCH_DEV}"$BE
+    echo "--------------------------------------------------------"
+    git push origin ${BRANCH_DEV}
   fi
 fi
